apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.200-172.18.255.240
    # Adjust this to match Docker's network: docker network inspect kind | jq '.[0].IPAM.Config[].Subnet'
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adv
  namespace: metallb-system
